team_musis:
    resource: "@TeamMusisBundle/Resources/config/routing.yml"
    prefix:   /

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"