team_musis_homepage:
    path:     /
    defaults: { _controller: TeamMusisBundle:Default:index }

team_musis_listallplaylist:
    path:     /listAllPlaylist
    defaults: { _controller: TeamMusisBundle:ListAllPlaylist:index }